Refactor for Asynchronous control flow
OpenTreeMap/otm-android pull request #298
Opened 2017-01-04 02:20 UTC by RobinIsTheBird

Rollbar registered the following error:
```
java.lang.NullPointerException: Attempt to invoke virtual method
'void com.google.android.gms.maps.GoogleMap.moveCamera(
    com.google.android.gms.maps.CameraUpdate)'
on a null object reference

at org.azavea.otm.ui.MainMapFragment.lambda$null$3
    (MainMapFragment.java:488)
```

It's probably a race condition.
Tame the asynchronous control flow to eliminate race conditions.

AFAIK, this fixes all race conditions except open question #1 below.
Unknown how many rollbar errors it will eliminate, but should
eliminate the original npe.

Refer to
* [MapView](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView)
* [GoogleMap](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap)
* [MapsInitializer](https://developers.google.com/android/reference/com/google/android/gms/maps/MapsInitializer)
* [GoogleApiAvailability](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability)
* [Fragment Life Cycle](https://developer.android.com/guide/components/fragments.html)

Changes:

- Use jDeferred to synchronize between asynchronous flows
- Move most initialization from onCreateView to `onActivityCreated`
- Move google api connect, map fetch, and add mode cancel to `onStart`
- Update `MapHelper` to use current google availability api

Open questions:

1. Need a way to manage the `MapHelper` google api dialog to determine
   whether the play store services problem gets resolved,
   and fail catastrophically if it doesn't.
2. Need a way to test missing play store services without wrecking my phone.
3. Fails to fix #297, clearing the filter repositions the camera
4. Probably shouldn't create new `Deferred` objects if they
   already exist, but haven't noticed any negative effects of doing so
5. I don't know enough about the tile cache to be sure when it needs
   to be cleared.

--

Connects to #294

2017-01-04 17:10 UTC, maurizi requested changes
Overall this is a really good change, much nicer code with a lot fewer foot-guns lying around.

I haven't tested it yet, I'll wait until you make the requested changes to do so.

2017-01-04 17:10 UTC, maurizi commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MapHelper.java
> +    // TODO: This ought to return the dialog for the sake of life cycle management.
I don't understand this comment - why would we do this? What would the calling Fragment or Activity do with the returned Dialog?

2017-01-04 17:10 UTC, maurizi commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +        // between a cleared filter and an instance reload at the moment.
can you update this TODO comment to reflect the discussion we had earlier today?

2017-01-04 17:10 UTC, maurizi commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +        boolean isFilterProviderNotSetup = filterTileProvider == null;
I don't think this boolean is necessary - it will _always_ be false here, as `filterTileProvider` is initialized in `setupTileProviders` right after this call.  I think you can eliminate it here, as well as remove the parameter from `setProviderDisplayParameters`

2017-01-04 17:10 UTC, maurizi commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +    private void moveToCurrentLocation(Location loc) {
Calling this method `moveToCurrentLocation` is a misnomer now, since it is passed a location.  Either it should retrieve the `Location` directly from the `locationPromise` or it should be renamed to `moveToLocation`

2017-01-06 14:21 UTC, RobinIsTheBird commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +                initLocation(treeMap, locationPromise, mMap).always((state, resolved, rejected) ->
It turns out that I had the lambda syntax wrong originally. Forgot it required parentheses around multiple arguments, and the error message wasn't helpful.

2017-01-06 16:11 UTC, maurizi requested changes

2017-01-06 16:11 UTC, maurizi commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +        }
As we discussed this check doesn't need to be here.

2017-01-06 16:11 UTC, maurizi commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +        // current or default location all over again.
As we discussed, I don't think this is a case that can occur.

2017-01-06 16:11 UTC, maurizi commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +        // except setupTileProviders.
As we discussed, I don't think this is a case that can occur

2017-01-06 18:27 UTC, RobinIsTheBird commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +        // doesn't seem like a good reason to make them start over.
If they switch apps, e.g. through the Recents display or by tapping a notification, OTM becomes invisible, and `onStop` notifications will trickle down through the activity to the fragment. Switching back, either by the back button, the Recents display, the Launcher, or the Home screen will result in `onStart`.

Simply losing focus without going invisible - that I'm not so sure of. I suppose there might be apps that do notifications, where tapping the notification just shows a dialog that doesn't cover the screen. I think my security app does that.

In any case, I don't think we should cancel during loss of focus, which is what used to be the case. If @dboyer would rather not cancel during invisibility, we could move this into `onActivityCreated`.

2017-01-06 18:52 UTC, RobinIsTheBird commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MapHelper.java
> +    // TODO: This ought to return the dialog for the sake of life cycle management.
I was hoping that the dialog would have a listener interface to discover whether the Play Services issue is fixed, but apparently it does not. I'll remove the comment.

2017-01-06 18:55 UTC, maurizi requested changes

2017-01-06 18:55 UTC, maurizi commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +        // doesn't seem like a good reason to make them start over.
If we don't want to cancel during loss of focus, we can remove this altogether I think 🙂

2017-01-09 23:11 UTC, RobinIsTheBird commented
If this rev passes review, I'll rebase/squash onto master.

2017-01-10 14:54 UTC, RobinIsTheBird commented on OpenTreeMap/src/main/java/org/azavea/otm/ui/MainMapFragment.java
> +    private Deferred<GoogleMap, Throwable, Void> mMapSetupDeferred = new DeferredObject<>();
It would make sense now to replace this with a Promise of the same signature and move the deferred into onActivityCreated, but not sure it's worth it, especially since the tests of the promise member would then have to all check for null, since the Promise must be created from the Deferred. So leaving the Deferred as a member for now.

2017-01-10 17:30 UTC, maurizi approved these changes
Code looks good, and everything seems to be working correctly!

Remember to rebase before merging :)

2017-01-10 19:42 UTC, merged